language: c

sudo: required

os:
  - linux

env:
  - OCAML_VERSION=4.05

before_install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - wget http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.3.tar.gz
  - sudo apt-get install opam ocaml llvm llvm-runtime m4

install:
  - opam --version
  - opam init --yes --no-setup
  - opam install depext llvm --yes

before_script:
  - eval `opam config env` --auto-setup
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sleep 3

script:
  - make clean all
  - ./testall.sh
  - cat testall.log

notifications:
  email: false